### ISSUE TITLE
Squadmanager

### ISSUE THREAD

**Issue by DeRampage** [TaskForce47/TF47-Gadget#1]
Egal was man einträgt es wird nicht übernommen!

Copy XML geht nicht

**Comment by RednecksRevenge** [comment]
Fehler in der Api @DragonGER

**Comment by NeutraleNull** [comment]
Sorry @RednecksRevenge :D
Fixed with https://github.com/TaskForce47/TF47-API/commit/c92f330a8d77f602f2991e0ec9f30316e1c5f5cf
